### ISSUE TITLE
uses a deprecated API

### ISSUE THREAD

**Issue by inishantsaharan** [devsonuyadav/one-react-native-upi#1]
node_modules/one-react-native-upi/android/src/main/java/com/onereactnativeupi/com/onereactnativeupi/OneReactNativeUpiModule.java uses or overrides a deprecated API.

can anyone tell me why I'm facing this issue ?

**Comment by tneupaney** [comment]
Add
`import com.facebook.react.module.annotations.ReactModule;`

in 
`node_modules/one-react-native-upi/android/src/main/java/com/onereactnativeupi/com/onereactnativeupi/OneReactNativeUpiModule.java`
