### ISSUE TITLE
You are trying to send money to a blocked VPA

### ISSUE THREAD

**Issue by ShravanMeena** [devsonuyadav/one-react-native-upi#3]
I tried with multiple merchant id but got same error

**Screenshots**
![WhatsApp Image 2023-05-31 at 7 03 44 PM](https://github.com/devsonuyadav/one-react-native-upi/assets/41790742/22d4086f-9781-486c-a2ff-cc421a4c5d1a)

Please help me out with this bug

**Comment by sonuwise** [comment]
@ShravanMeena please check the upi id once again. This error is thrown when the payments app is unable to verify the merchant

**Comment by ShravanMeena** [comment]
> @ShravanMeena please check the upi id once again. This error is thrown when the payments app is unable to verify the merchant

I tried with multiple UPI id. I went to shops and try but did not work

**Comment by devsonuyadav** [comment]
> > @ShravanMeena please check the upi id once again. This error is thrown when the payments app is unable to verify the merchant
> 
> I tried with multiple UPI id. I went to shops and try but did not work

Your upi ID should be a merchant account

**Comment by ShravanMeena** [comment]
Solved

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @ShravanMeena 
I am also facing similar issue. can you tell me how you managed to solve it. And I am unable to send money to non-Marchant IDs using their UPI ID.
